swagger: "2.0"
info:
  version: 0.0.1
  title: FlexiWAN
paths:
  /users/login:
    post:
      summary: Logs in a registered user
      tags:
      - 'Users'
      produces:
      - application/json
      parameters:
        - in: body
          description: User credentials
          name: body
          required: true
          schema:
            $ref: '#components/schemas/UserLoginRequest'
      responses:
        200:
          description: User is logged in to the system
          schema:
            $ref: '#components/schemas/UserLoginResponse'
        403:
          description: Invalid user credentials
          schema:
            $ref: '#components/schemas/BadCredentials'